#!/usr/bin/env ruby
source "https://rubygems.org"

gem "whiskey", "<%= Whiskey::VERSION %>"

gem "sqlite3", "~> 1.3"
# gem "pg", "~> 0.14"
# gem "mysql2", "~> 0.3"
# gem "redis", "~> 3.0"
# gem "dalli", "~> 2.6"
