#!/usr/bin/env ruby
source "https://rubygems.org"

gem "whiskey", "<%= Whiskey::VERSION %>", github: "krainboltgreene/whiskey"

gem "sqlite3", "~> 1.3"
group :production do
  # gem "pg", "~> 0.14"
  # gem "mysql2", "~> 0.3"
  # gem "redis", "~> 3.0"
  # gem "dalli", "~> 2.6"
end

